// GENERATED CODE -- DO NOT EDIT!
//
// This file is automatically generated by the Superblocks CLI
// Use the `superblocks components watch` command to regenerate this file from its source in config.ts

// All properties of your component are defined here.
// These are the properties which are surfaced in the Superblocks properties panel
// and can be referenced throughout your Superblocks Application
export type Props = {
  uid: string | null;
  name: string | null;
  enableAttachments: boolean;
  enableComments: boolean;
  enableCloudFiles: boolean;
  enableMentions: boolean;
  enablePreviews: boolean;
  enableReactions: boolean;
  enableVersions: boolean;
  enableWebDAV: boolean;
  enableNotifications: boolean;
  forceDarkMode: boolean;
  theme: any;
  weavyUrl: string | null;
  accessToken: string | null;
  weavyOptions: any;
};

export type EventTriggers = {
  // Call the subsequent function(s) to trigger event(s) in Superblocks from your component.
  // These events can be wired up to event handlers in your Superblocks App
  onSetWeavyNavigation: () => void;
  onTokenExpired: () => void;
};
