// GENERATED CODE -- DO NOT EDIT!
//
// This file is automatically generated by the Superblocks CLI
// Use the `superblocks components watch` command to regenerate this file from its source in config.ts

// All properties of your component are defined here.
// These are the properties which are surfaced in the Superblocks properties panel
// and can be referenced throughout your Superblocks Application
export type Props = {
  agent: string | null;
  instructions: string | null;
  contextData: string | null;
  suggestions: any;
  enableNewButton: boolean;
  uid: string | null;
  enableAutoUid: boolean;
  name: string | null;
  enableEmbeds: boolean;
  enableMentions: boolean;
  enablePreviews: boolean;
  enableReactions: boolean;
  enableTyping: boolean;
  enableNotifications: boolean;
  forceDarkMode: boolean;
  theme: any;
  weavyUrl: string | null;
  accessToken: string | null;
  weavyOptions: any;
  appId: number | null;
  lastMessage: any;
};

export type EventTriggers = {
  // Call the subsequent function(s) to trigger event(s) in Superblocks from your component.
  // These events can be wired up to event handlers in your Superblocks App
  onSetWeavyNavigation: () => void;
  onTokenExpired: () => void;
  onApp: () => void;
  onMessage: () => void;
};
